#pragma once

#define KERNEL_CS_INDEX 1
#define KERNEL_SS_INDEX (KERNEL_CS_INDEX+1)
#define USER_CS32_INDEX 3
#define USER_SS_INDEX (USER_CS32_INDEX+1)
#define USER_CS_INDEX (USER_SS_INDEX+1)
#define TSS_INDEX 6
#define KERNEL_CS (KERNEL_CS_INDEX<<3)
#define KERNEL_SS (KERNEL_SS_INDEX<<3)
#define USER_CS32 ((USER_CS32_INDEX<<3)|0x3)
#define USER_CS ((USER_CS_INDEX<<3)|0x3)
#define USER_SS ((USER_SS_INDEX<<3)|0x3)
#define TSS (TSS_INDEX<<3)
